# Generated by Django 4.0.6 on 2022-08-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musics',
            new_name='Music',
        ),
    ]
